using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorsLibrary;

public class GeneratorInternal<TGenerator>
    where TGenerator : IIncrementalGenerator, new()
{
    private static Type GeneratorType => typeof(TGenerator);
    protected static string GeneratorName => GeneratorType.Name;
    protected static string AttributeName => GeneratorName.Replace("Generator", "Attribute");
    protected static string GeneratorNamespace => GeneratorType.Namespace;

    protected static void CreateAttribute(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource($"{AttributeName}.g.cs", SourceText.From(AttributeFile, Encoding.UTF8)));

    private static string AttributeFile => $$"""
        // <auto-generated />
        // {{DateTime.Now:yyyy-MM-dd HH:mm:ss.fff}}

        namespace {{GeneratorNamespace}};

        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class {{AttributeName}} : System.Attribute {}
        """;

    protected static bool IsCandidate(SyntaxNode node) =>
        node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0;
}
