using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorsLibrary;

[Generator]
public sealed class GenerateBinarySerializerGenerator : GeneratorInternal<GenerateBinarySerializerGenerator>, IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#pragma warning disable S125 // Sections of code should not be commented out
        //#if DEBUG
        //        if (!Debugger.IsAttached)
        //        {
        //            Debugger.Launch();
        //        }
        //#endif
#pragma warning restore S125 // Sections of code should not be commented out

        // Create attribute
        CreateAttribute(context);

        // Find all class declarations with attribute
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s), // quick filter
                transform: static (ctx, _) => GetSemanticTarget(ctx)) // get symbol
            .Where(static m => m is not null)!;

        // Generate code for each matched class
        context.RegisterSourceOutput(classDeclarations, static (spc, classSymbol) =>
            GenerateSerializer(spc, classSymbol!));
    }

    private static void GenerateSerializer(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        var @namespace = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;

        var props = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic)
            .Where(p => p.GetMethod is not null)
            .Where(p => p.SetMethod is not null)
            .Where(p => p.DeclaredAccessibility == Accessibility.Public)
            .Where(p => IsSupportedType(p.Type))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// {DateTime.Now:yyyy-MM-dd HH:mm:ss.fff}");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(@namespace))
        {
            sb.Append("namespace ").Append(@namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("public partial class ").Append(className).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    public void SerializeToBinary(Stream stream)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var writer = new BinaryWriter(stream, System.Text.Encoding.UTF8, true);");
        sb.AppendLine();

        foreach (var prop in props)
            AppendWriteForProperty(sb, prop);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendWriteForProperty(StringBuilder sb, IPropertySymbol prop)
    {
        switch (prop.Type.SpecialType)
        {
            case SpecialType.System_Int32:
                sb.Append("        writer.Write(this.")
                  .Append(prop.Name)
                  .AppendLine(");");
                break;

            case SpecialType.System_String:
                sb.AppendLine("        if (this." + prop.Name + " == null)");
                sb.AppendLine("        {");
                sb.AppendLine("            writer.Write(-1);");
                sb.AppendLine("        }");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine("            var buffer = ArrayPool<byte>.Shared.Rent(Username.Length);");
                sb.AppendLine("            var memory = new Memory<byte>(buffer);");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine("                var length = Encoding.UTF8.GetBytes(this." + prop.Name + ", memory.Span);");
                sb.AppendLine("                writer.Write(length);");
                sb.AppendLine("                writer.Write(memory.Span[..length]);");
                sb.AppendLine("            }");
                sb.AppendLine("            finally");
                sb.AppendLine("            {");
                sb.AppendLine("                ArrayPool<byte>.Shared.Return(buffer);");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                break;

            case SpecialType.System_DateTime:
                sb.Append("        writer.Write(this.")
                  .Append(prop.Name)
                  .AppendLine(".ToBinary());");
                break;

            default:
                sb.Append("        // Unsupported type: ")
                  .Append(prop.Type.SpecialType)
                  .AppendLine();
                break;
        }
        sb.AppendLine();
    }
    private static bool IsSupportedType(ITypeSymbol type) =>
        type.SpecialType switch
        {
            SpecialType.System_Int32 or SpecialType.System_DateTime or SpecialType.System_String => true,
            _ => false,
        };
}
